# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{blueprintr}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["cbrumelle"]
  s.date = %q{2010-05-11}
  s.default_executable = %q{blueprintr}
  s.description = %q{A gem wrapper to ease the use of the Blueprint CSS framework (http://www.blueprintcss.org). This gem gives you the latest version of Blueprint CSS (0.9.1).}
  s.email = %q{colin@mixedcontent.com}
  s.executables = ["blueprintr"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/blueprintr",
     "blueprintr.gemspec",
     "lib/blueprint-css/.gitignore",
     "lib/blueprint-css/AUTHORS.textile",
     "lib/blueprint-css/CHANGELOG",
     "lib/blueprint-css/LICENSE",
     "lib/blueprint-css/README.textile",
     "lib/blueprint-css/TUTORIAL.textile",
     "lib/blueprint-css/blueprint/ie.css",
     "lib/blueprint-css/blueprint/plugins/buttons/icons/cross.png",
     "lib/blueprint-css/blueprint/plugins/buttons/icons/key.png",
     "lib/blueprint-css/blueprint/plugins/buttons/icons/tick.png",
     "lib/blueprint-css/blueprint/plugins/buttons/readme.txt",
     "lib/blueprint-css/blueprint/plugins/buttons/screen.css",
     "lib/blueprint-css/blueprint/plugins/fancy-type/readme.txt",
     "lib/blueprint-css/blueprint/plugins/fancy-type/screen.css",
     "lib/blueprint-css/blueprint/plugins/link-icons/icons/doc.png",
     "lib/blueprint-css/blueprint/plugins/link-icons/icons/email.png",
     "lib/blueprint-css/blueprint/plugins/link-icons/icons/external.png",
     "lib/blueprint-css/blueprint/plugins/link-icons/icons/feed.png",
     "lib/blueprint-css/blueprint/plugins/link-icons/icons/im.png",
     "lib/blueprint-css/blueprint/plugins/link-icons/icons/pdf.png",
     "lib/blueprint-css/blueprint/plugins/link-icons/icons/visited.png",
     "lib/blueprint-css/blueprint/plugins/link-icons/icons/xls.png",
     "lib/blueprint-css/blueprint/plugins/link-icons/readme.txt",
     "lib/blueprint-css/blueprint/plugins/link-icons/screen.css",
     "lib/blueprint-css/blueprint/plugins/rtl/readme.txt",
     "lib/blueprint-css/blueprint/plugins/rtl/screen.css",
     "lib/blueprint-css/blueprint/print.css",
     "lib/blueprint-css/blueprint/screen.css",
     "lib/blueprint-css/blueprint/src/forms.css",
     "lib/blueprint-css/blueprint/src/grid.css",
     "lib/blueprint-css/blueprint/src/grid.png",
     "lib/blueprint-css/blueprint/src/ie.css",
     "lib/blueprint-css/blueprint/src/print.css",
     "lib/blueprint-css/blueprint/src/reset.css",
     "lib/blueprint-css/blueprint/src/typography.css",
     "lib/blueprint-css/lib/blueprint/blueprint.rb",
     "lib/blueprint-css/lib/blueprint/compressor.rb",
     "lib/blueprint-css/lib/blueprint/core_ext.rb",
     "lib/blueprint-css/lib/blueprint/css_parser.rb",
     "lib/blueprint-css/lib/blueprint/custom_layout.rb",
     "lib/blueprint-css/lib/blueprint/grid.css.erb",
     "lib/blueprint-css/lib/blueprint/grid_builder.rb",
     "lib/blueprint-css/lib/blueprint/namespace.rb",
     "lib/blueprint-css/lib/blueprint/semantic_class_names.rb",
     "lib/blueprint-css/lib/blueprint/validate/COPYRIGHT.html",
     "lib/blueprint-css/lib/blueprint/validate/JIGSAW_COPYRIGHT",
     "lib/blueprint-css/lib/blueprint/validate/README.html",
     "lib/blueprint-css/lib/blueprint/validate/XERCES_COPYING.txt",
     "lib/blueprint-css/lib/blueprint/validate/css-validator-javadoc.jar",
     "lib/blueprint-css/lib/blueprint/validate/css-validator.jar",
     "lib/blueprint-css/lib/blueprint/validate/jigsaw.jar",
     "lib/blueprint-css/lib/blueprint/validate/xerces.jar",
     "lib/blueprint-css/lib/blueprint/validator.rb",
     "lib/blueprint-css/lib/compress.rb",
     "lib/blueprint-css/lib/settings.example.yml",
     "lib/blueprint-css/lib/validate.rb",
     "lib/blueprint-css/templates/psd/fixed-width.psd",
     "lib/blueprint-css/tests/index.html",
     "lib/blueprint-css/tests/parts/elements.html",
     "lib/blueprint-css/tests/parts/forms.html",
     "lib/blueprint-css/tests/parts/grid.html",
     "lib/blueprint-css/tests/parts/sample.html",
     "lib/blueprint-css/tests/parts/test-small.jpg",
     "lib/blueprint-css/tests/parts/test.jpg",
     "lib/blueprint-css/tests/parts/valid.png",
     "lib/blueprintr.rb",
     "test/helper.rb",
     "test/test_blueprintr.rb"
  ]
  s.homepage = %q{http://github.com/cbrumelle/blueprintr}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A gem wrapper to ease the use of the Blueprint CSS framework (http://www.blueprintcss.org)}
  s.test_files = [
    "test/helper.rb",
     "test/test_blueprintr.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

